### ISSUE TITLE
Using rqt_top for remote machine

### ISSUE THREAD

**Issue by AchmadFathoni** [ros-visualization/rqt_top#4]
I want to monitor from my laptop the ROS resource usage on robot that use embedded SBC. I use wifi access point and ssh to communicate and in this case ROS mater run on the robot.  Can rqt_top do that? is there any limitation?

**Comment by Combinacijus** [comment]
I know it's a late answer but this issue can be closed now and might help others

You need to setup [ROS over network](http://wiki.ros.org/ROS/NetworkSetup) which basically means that you have to set correct environmental variables ROS_MASTER_URI and ROS_IP on both computers I usually do it by alias or in ~/.bashrc file
But if you change IPs to your robot's computer then you won't be able to run ROS on you own computer without master node from robot that's why I use aliases to more easily change IPs back

(192.168.8.103) My laptop side aliases in ~/.bashrc file:
```
unset ROS_IP
alias ros_robot="export ROS_MASTER_URI=http://192.168.8.104:11311; export ROS_IP=192.168.8.103"
alias ros_laptop="export ROS_MASTER_URI=http://localhost:11311"
ros_robot
```

(192.168.8.104) Robot's computer side in ~/.bashrc file:
```
alias ros_robot="export ROS_MASTER_URI=http://192.168.8.104:11311; export ROS_IP=192.168.8.104"
ros_robot
```

`ROS_MASTER_URI` is address of machine which runs roscore
`ROS_IP` is address (no substitutions allowed) to machine it's running

To run ROS on laptop just run `unset ROS_IP` and `rqt_laptop` that resets network configuration.
